const projects = [
    {
        id: 1,
        title: "Lumina Commerce",
        category: "web-ecom",
        categoryLabel: "Ecommerce",
        shortDesc: "A high-end minimal e-commerce experience scaling user conversions by 45%.",
        image: "assets/ecom.png",
        problem: "Lumina's outdated storefront was leaking revenue. The user experience was friction-heavy, and mobile drop-offs were massive.",
        solution: "We architected a headless Shopify ecosystem using Next.js and Tailwind CSS, focusing on micro-interactions and sensory design.",
        techStack: ["Next.js", "Shopify Plus", "Tailwind CSS", "Framer Motion"],
        result: "45% increase in mobile conversions and a 200% boost in overall brand prestige. Load speeds dropped to under 1s.",
        liveLink: "https://lumina.example.com",
        githubLink: "https://github.com/demaryx/lumina-core"
    },
    {
        id: 2,
        title: "Apex Web Studio",
        category: "web-ecom",
        categoryLabel: "Web Design",
        shortDesc: "A bold, dark-mode landing page designed to attract high-ticket clients.",
        image: "assets/webdev.png",
        problem: "Apex had extreme difficulty converting leads because their aesthetic didn't match the high-ticket price of their corporate offerings.",
        solution: "Implementing a deep-dark aesthetic with neon glows and heavy glassmorphism, we structured a narrative-driven landing page.",
        techStack: ["React", "GSAP Animations", "Three.js", "Vercel"],
        result: "Lead generation skyrocketed. They began attracting Fortune 500 inquiries within 2 weeks of launch.",
        liveLink: "https://apex.example.com",
        githubLink: "https://github.com/demaryx/apex-studio"
    },
    {
        id: 3,
        title: "Onyx Analytics",
        category: "ai-auto",
        categoryLabel: "AI & Automation",
        shortDesc: "A futuristic AI-driven dashboard that automates daily operational reporting.",
        image: "assets/ai.png",
        problem: "Data analysts were spending 15 hours a week just compiling data streams manually. The business needed intelligence, not just data entry.",
        solution: "We created a deeply integrated AI engine and wrapped it in a stunning graphical interface, providing predictive metrics.",
        techStack: ["Python", "OpenAI API", "React", "PostgreSQL"],
        result: "100% automation of basic operational reporting. Decision makers now act 5x faster with accurate forecasting.",
        liveLink: "https://onyxdash.example.com",
        githubLink: "https://github.com/demaryx/onyx-engine"
    },
    {
        id: 4,
        title: "Verve Identity",
        category: "branding",
        categoryLabel: "Brand Growth",
        shortDesc: "A complete visual overhaul to position Verve as the leading social network.",
        image: "assets/branding.png",
        problem: "Verve struggled to stand out in a saturated market. Their brand lacked soul, impact, and a clear story to connect with Gen-Z users.",
        solution: "A bold, unapologetic typography foundation coupled with dynamic collateral that looks premium and futuristic.",
        techStack: ["Adobe CC", "Figma", "Cinema 4D", "Brand Strategy"],
        result: "The visual reboot helped close their $5M Series A funding round with extreme investor confidence.",
        liveLink: "https://verve.example.com",
        githubLink: "https://github.com/demaryx/verve-assets"
    },
    {
        id: 5,
        title: "Sahvex Tech",
        category: "branding",
        categoryLabel: "Branding",
        shortDesc: "Modernizing a legacy tech firm with a sharp, geometric visual identity.",
        image: "assets/logo branding/sahvex logo.jpg",
        problem: "Sahvex had been using the same logo since 1998. It looked dated and didn't reflect their transition into cloud computing.",
        solution: "Developed a 'Security-First' design language using interlocking geometric shapes and a custom high-contrast color palette.",
        techStack: ["Figma", "Vector Motion", "Illustrator"],
        result: "30% increase in brand recognition within the B2B tech space and unified global marketing efforts.",
        liveLink: "#",
        githubLink: "#"
    },
    {
        id: 6,
        title: "Lucid Origin",
        category: "branding",
        categoryLabel: "Luxury Branding",
        shortDesc: "Elite-tier branding for a boutique luxury consultancy.",
        image: "assets/logo branding/lucid-origin_Create_a_premium_luxury_branding_presentation_for_a_Resume_Designer_business._Sh-0.jpg",
        problem: "Lucid Origin targets high-net-worth individuals. Their previous brand felt 'corporate' and 'stale'.",
        solution: "A 'Luxury-Minimal' approach using expensive-looking textures and a serif-first typography system.",
        techStack: ["Brand Audit", "Premium Assets", "Typography Design"],
        result: "Allowed Lucid Origin to double their consultation fees within 2 months due to increased perceived value.",
        liveLink: "#",
        githubLink: "#"
    },
    {
        id: 7,
        title: "Softfeel Cosmetics",
        category: "branding",
        categoryLabel: "Brand Identity",
        shortDesc: "A sensory-driven visual identity for a premium skincare line.",
        image: "assets/logo branding/softfeel.png",
        problem: "Softfeel's products are about texture, but their brand was clinical and boring. They failed to convey the 'Softfeel' experience.",
        solution: "Implemented 'Sensory Design' using macro photography styles and a muted color palette that mirrors physical products.",
        techStack: ["Visual Identity", "Package Design", "Art Direction"],
        result: "60% increase in brand engagement and a significant jump in returning customer rates.",
        liveLink: "#",
        githubLink: "#"
    },
    {
        id: 8,
        title: "Quantum Systems",
        category: "app-dash",
        categoryLabel: "Dashboard Design",
        shortDesc: "Revolutionizing data visualization for quantum computing research.",
        image: "assets/logo branding/image_e7dbfa18.png",
        problem: "Quantum researchers were dealing with complex data outputs that were unreadable in standard graph formats.",
        solution: "Built a WebGL-powered data dashboard that translates complex quantum states into interactive 3D models.",
        techStack: ["Three.js", "WebGL", "React", "D3.js"],
        result: "Research speed increased by 40% as scientists could visually identify anomalies in the data.",
        liveLink: "#",
        githubLink: "#"
    },
    {
        id: 9,
        title: "Urban Glow",
        category: "branding",
        categoryLabel: "Branding",
        shortDesc: "Dynamic identity for a high-end street-wear fashion label.",
        image: "assets/logo branding/image_bfeed796.png",
        problem: "Urban Glow needed to bridge the gap between luxury fashion and gritty street culture.",
        solution: "Combined high-fashion serif fonts with 'glitch' effect graphics and a high-saturation 'Cyber-City' color scheme.",
        techStack: ["Identity System", "Motion Graphics", "Social Strategy"],
        result: "Successful launch with a 100% sell-out of their first collection within 48 hours.",
        liveLink: "#",
        githubLink: "#"
    },
    {
        id: 10,
        title: "Nexus UI",
        category: "branding",
        categoryLabel: "UI System",
        shortDesc: "A clean, high-performance visual system for a next-gen cloud platform.",
        image: "assets/logo branding/logo34.png",
        problem: "Nexus was losing users during onboarding. The interface was cluttered and overwhelmed new sign-ups.",
        solution: "A 'Progressive Disclosure' UI system, focusing the main dashboard on key performance indicators.",
        techStack: ["Design System", "React Components", "Framer"],
        result: "User retention increased by 25% and support tickets dropped by 40%.",
        liveLink: "#",
        githubLink: "#"
    },
    {
        id: 11,
        title: "Silver Line",
        category: "branding",
        categoryLabel: "Branding",
        shortDesc: "Visual identity for a boutique architectural firm.",
        image: "assets/logo branding/2.jpg",
        problem: "Silver Line's branding didn't reflect the precision and 'clean lines' of their architectural work.",
        solution: "A 'Structural' branding system where the logo is built on a mathematical grid, mirroring blueprints.",
        techStack: ["Geometric Design", "Grid Systems", "Minimalism"],
        result: "Won 3 major commercial bids in the first quarter post-rebrand.",
        liveLink: "#",
        githubLink: "#"
    },
    {
        id: 12,
        title: "Titan Group",
        category: "branding",
        categoryLabel: "Corporate Branding",
        shortDesc: "A powerful, industrial-strength identity for a global logistics giant.",
        image: "assets/logo branding/10818.jpg",
        problem: "Titan Group felt like a 'generic' logistics company and lacked scale in their brand image.",
        solution: "Used heavy, bold typography and a 'Steel & Cobalt' color palette inspired by shipping modules.",
        techStack: ["Corporate ID", "Wayfinding", "Global Guidelines"],
        result: "Unified 15 sub-brands under a single power-house identity, simplifying global communication.",
        liveLink: "#",
        githubLink: "#"
    },
    {
        id: 13,
        title: "UGC Ad — Raw Authority",
        category: "ugc-ads",
        categoryLabel: "UGC Ads",
        shortDesc: "High-converting UGC ad for a premium brand — authentic storytelling that stops the scroll.",
        video: "assets/ugc ads/01.mp4",
        image: "",
        problem: "The brand was spending heavily on polished studio ads but seeing minimal ROI. Audiences had ad fatigue and weren't converting from traditional creative.",
        solution: "We produced a raw, authentic UGC-style video ad that mimics organic content. Real hook in the first 2 seconds, problem-agitate-solve script, strong CTA — engineered for mobile feed dominance.",
        techStack: ["UGC Script", "Mobile-First Filming", "Hook Engineering", "Meta Ads"],
        result: "3.2x ROAS on first week of launch. CTR jumped from 0.8% to 4.7%. Cost per purchase dropped by 62%.",
        growthPoints: [
            { icon: "📈", title: "ROAS 3.2x", desc: "Revenue tripled on ad spend within the first week of deployment." },
            { icon: "🎯", title: "CTR 4.7%", desc: "Click-through rate soared from 0.8% — 5x industry average." },
            { icon: "💰", title: "62% Lower CPA", desc: "Cost per purchase dropped dramatically, maximizing budget efficiency." },
            { icon: "🔥", title: "Scroll-Stop Hook", desc: "First 2-second hook engineered to stop thumb scrolling in busy feeds." }
        ],
        liveLink: "#",
        githubLink: "#"
    },
    {
        id: 14,
        title: "UGC Ad — Social Proof Drop",
        category: "ugc-ads",
        categoryLabel: "UGC Ads",
        shortDesc: "Testimonial-style UGC ad engineered for trust-building and repeat purchases.",
        video: "assets/ugc ads/02.mp4",
        image: "",
        problem: "Low trust was killing conversions. Potential customers were visiting product pages but abandoning without purchasing — classic trust gap in a saturated market.",
        solution: "Created a testimonial-style UGC ad with real-feel delivery, leveraging psychological social proof triggers and urgency cues without feeling scripted or forced.",
        techStack: ["Testimonial Script", "Social Proof Psychology", "TikTok Ads", "Retention Editing"],
        result: "Purchase conversion rate went from 1.2% to 4.8%. Brand trust score increased 40% per post-survey data.",
        growthPoints: [
            { icon: "🤝", title: "Trust Engineered", desc: "Authentic testimonial format built instant credibility with cold audiences." },
            { icon: "📊", title: "CVR 4.8%", desc: "Conversion rate nearly quadrupled from baseline 1.2%." },
            { icon: "🔁", title: "Repeat Purchases", desc: "Returning customer rate increased by 28% in the 30 days post-launch." },
            { icon: "🚀", title: "TikTok Dominance", desc: "Ad achieved organic-level engagement, extending reach beyond paid." }
        ],
        liveLink: "#",
        githubLink: "#"
    },
    {
        id: 15,
        title: "UGC Ad — Problem Solver",
        category: "ugc-ads",
        categoryLabel: "UGC Ads",
        shortDesc: "Pain-point focused UGC ad that converts cold traffic into buyers in 30 seconds.",
        video: "assets/ugc ads/03.mp4",
        image: "",
        problem: "Product had strong organic reviews but couldn't convert cold paid traffic. The existing ads were too 'salesy' and audiences were scrolling past within 1-2 seconds.",
        solution: "Built a pain-point lead UGC video — open with the exact problem, demonstrate the solution naturally, close with a value-driven CTA. Edited for maximum watch time retention.",
        techStack: ["Pain-Point Script", "Watch-Time Optimization", "Instagram Reels", "A/B Testing"],
        result: "Average watch time 78% (industry avg: 25%). Conversion from cold traffic: 3.9%. ROI: 4.1x in first month.",
        growthPoints: [
            { icon: "👁️", title: "78% Watch Time", desc: "Audience watched nearly the full ad — 3x better than industry average." },
            { icon: "❄️", title: "Cold Traffic Wins", desc: "3.9% conversion from cold audiences who had never seen the brand." },
            { icon: "💡", title: "Problem-Led Hook", desc: "Opening with the exact pain point created immediate emotional resonance." },
            { icon: "📱", title: "Reels Domination", desc: "Organic shares extended reach 2x beyond the paid audience." }
        ],
        liveLink: "#",
        githubLink: "#"
    },
    {
        id: 16,
        title: "Vyron x Energy Drink",
        category: "ugc-ads",
        categoryLabel: "UGC Ads",
        shortDesc: "High-energy brand collaboration ad for Vyron Energy — lifestyle meets performance.",
        video: "assets/ugc ads/vyron x enegy drink .mp4",
        image: "",
        problem: "Vyron Energy needed to break into a market dominated by Red Bull and Monster. The brand had a great product but zero social presence and no digital creative assets.",
        solution: "Produced a high-energy UGC lifestyle ad pairing the product with peak-performance moments. Fast cuts, music sync, and authentic creator feel built brand personality from zero.",
        techStack: ["Lifestyle UGC", "Brand Building", "YouTube Shorts", "Energy Sector"],
        result: "Brand went from 0 to 12K followers in 45 days. Product sold out in first retail drop. Partnership with 3 gyms secured.",
        growthPoints: [
            { icon: "⚡", title: "0 to 12K Followers", desc: "Built a brand community from scratch in 45 days through strategic UGC content." },
            { icon: "🛒", title: "Sold Out Launch", desc: "First retail drop sold out within 72 hours of the ad campaign going live." },
            { icon: "🏋️", title: "3 Gym Partnerships", desc: "Brand credibility led to direct B2B partnerships with fitness venues." },
            { icon: "🎬", title: "Creator-Feel Content", desc: "Lifestyle-driven production made branded content feel native and shareable." }
        ],
        liveLink: "#",
        githubLink: "#"
    },
    {
        id: 17,
        title: "Premium Product Shoot — Hero Shot",
        category: "product-branding",
        categoryLabel: "Product Branding",
        shortDesc: "High-end hero product photography engineered to dominate e-commerce listings and paid ads.",
        image: "assets/PRODUCT branding/PRODUCT SHOOT 1.png",
        problem: "The client's product was premium quality but existing imagery was shot on a phone. Low-quality photos were killing conversions on Shopify and Amazon listings.",
        solution: "Studio-quality hero shot with premium lighting, composition, and post-production. Designed specifically for above-the-fold placement on product pages and Meta ad creatives.",
        techStack: ["Studio Photography", "Product Styling", "Post-Production", "E-commerce Optimized"],
        result: "Product page CVR increased from 1.8% to 5.2% after image swap. Ad CTR improved by 3.1x using the same hero shot.",
        liveLink: "#",
        githubLink: "#"
    },
    {
        id: 18,
        title: "Product Branding — Lifestyle A",
        category: "product-branding",
        categoryLabel: "Product Branding",
        shortDesc: "Lifestyle product photography designed to connect emotionally with the target audience.",
        image: "assets/PRODUCT branding/PRODUCT SHOOT 1 A.png",
        problem: "Generic white-background images weren't creating emotional connection with the brand's lifestyle-focused audience.",
        solution: "Lifestyle context photography placing the product in aspirational real-world settings, colour graded to match the brand's premium aesthetic.",
        techStack: ["Lifestyle Photography", "Colour Grading", "Brand Alignment", "Social Media Ready"],
        result: "Instagram engagement rate doubled. Story ads using lifestyle imagery achieved 6.2% swipe-up rate vs 1.4% industry average.",
        liveLink: "#",
        githubLink: "#"
    },
    {
        id: 19,
        title: "Product Branding — Lifestyle B",
        category: "product-branding",
        categoryLabel: "Product Branding",
        shortDesc: "Multi-angle product series for complete catalogue and social media coverage.",
        image: "assets/PRODUCT branding/PRODUCT SHOOT 1 B.png",
        problem: "Brand had one product angle. Customers couldn't visualise the full product, leading to high return rates and low purchase confidence.",
        solution: "Full 360-degree product series — front, side, detail close-ups, and in-use shots — giving customers a tactile understanding before purchase.",
        techStack: ["360 Product Series", "Detail Macro Shots", "Catalogue Design", "Shopify Optimized"],
        result: "Return rate dropped by 34%. Product page dwell time increased by 2.4 minutes as customers explored the full gallery.",
        liveLink: "#",
        githubLink: "#"
    },
    {
        id: 20,
        title: "Product Shoot — Commercial Grade",
        category: "product-branding",
        categoryLabel: "Product Branding",
        shortDesc: "Commercial-grade product photography for retail packaging and advertising campaigns.",
        image: "assets/PRODUCT branding/PRODUCT SHOOT 2.png",
        problem: "Brand was preparing to pitch to major retail chains but lacked professional product imagery for their pitch deck and packaging.",
        solution: "High-resolution commercial shoot with clean backgrounds, packshot variations, and retail-ready formats at 300dpi for print and digital use.",
        techStack: ["Commercial Photography", "Retail Ready Formats", "300dpi Print", "Packshot Design"],
        result: "Brand secured placement in 2 major retail outlets within 3 months. Photography used across all packaging and digital campaigns.",
        liveLink: "#",
        githubLink: "#"
    },
    {
        id: 21,
        title: "Product Visual — Premium Dark",
        category: "product-branding",
        categoryLabel: "Product Branding",
        shortDesc: "Dark-aesthetic product photography for luxury positioning and premium brand narrative.",
        image: "assets/PRODUCT branding/PRODUCT SHOOT 3.png",
        problem: "Brand wanted to reposition from mid-market to premium/luxury. Existing bright imagery communicated affordable — the opposite of their new direction.",
        solution: "Dark studio aesthetics with dramatic Rembrandt lighting, deep blacks, and gold accent highlights to visually communicate luxury and exclusivity.",
        techStack: ["Dark Studio Lighting", "Luxury Aesthetics", "Brand Repositioning", "Premium Retouching"],
        result: "Average order value increased by 40% post-rebrand. New imagery enabled a successful price increase without customer pushback.",
        liveLink: "#",
        githubLink: "#"
    },
    {
        id: 22,
        title: "Product Series — Texture & Detail",
        category: "product-branding",
        categoryLabel: "Product Branding",
        shortDesc: "Macro detail and texture photography that sells product quality before a word is read.",
        image: "assets/PRODUCT branding/PRODUCT SHOOT 3B.png",
        problem: "Physical product had exceptional material quality but online customers couldn't feel it — the brand was losing sales to cheaper competitors.",
        solution: "Close-up macro photography highlighting material grain, finish quality, and craftsmanship details that justify the premium price point.",
        techStack: ["Macro Photography", "Texture Detail", "Material Storytelling", "Premium Positioning"],
        result: "Reduced price-comparison drop-offs by 28%. Customer reviews began specifically mentioning quality expectations matching the product.",
        liveLink: "#",
        githubLink: "#"
    },
    {
        id: 23,
        title: "Product Shoot — Flat Lay Series",
        category: "product-branding",
        categoryLabel: "Product Branding",
        shortDesc: "Curated flat lay product compositions for Instagram, Pinterest, and catalogue use.",
        image: "assets/PRODUCT branding/PRODUCT SHOOT 4A.png",
        problem: "Brand struggled with content consistency on Instagram. Each post looked different, breaking the visual grid and confusing new visitors.",
        solution: "Cohesive flat lay series with a defined colour palette, consistent props, and spacing ratios — designed as a template system the client can replicate.",
        techStack: ["Flat Lay Styling", "Visual Grid System", "Content Template", "Instagram Strategy"],
        result: "Instagram profile visits up 85% after grid overhaul. Follower growth tripled in 60 days. Content save rate up 4x.",
        liveLink: "#",
        githubLink: "#"
    },
    {
        id: 24,
        title: "Product Campaign — Full Shoot",
        category: "product-branding",
        categoryLabel: "Product Branding",
        shortDesc: "Full campaign product shoot delivering hero images, social assets, and ad creatives in one session.",
        image: "assets/PRODUCT branding/PRODUCTS SHOOT 2A.png",
        problem: "Client was spending budget on 3-4 separate shoots per month for different use cases — website, social, ads — creating inconsistency and huge cost overhead.",
        solution: "One full-day campaign shoot producing 40+ images across hero, lifestyle, detail, and flat lay formats — unified visual language, maximum output.",
        techStack: ["Campaign Direction", "Multi-format Delivery", "Brand Consistency", "Batch Production"],
        result: "Monthly photography cost reduced by 70%. All digital channels now share a unified visual identity that drives consistent conversions.",
        liveLink: "#",
        githubLink: "#"
    }
];
